# Generated by Django 2.0.2 on 2019-05-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='词汇名称')),
                ('alias', models.CharField(max_length=50, null=True, verbose_name='词汇别名')),
                ('detail', models.CharField(default='软件开发术语', max_length=70, verbose_name='词汇描述')),
                ('father_type', models.CharField(max_length=50, null=True, verbose_name='父词汇类型')),
                ('root_type', models.CharField(max_length=50, verbose_name='根词汇类型')),
                ('img_url', models.CharField(max_length=100, verbose_name='图片路径')),
                ('system', models.CharField(choices=[('ai', '人工智能'), ('bigdata', '大数据'), ('couldcompute', '云计算'), ('blockchain', '区块链'), ('database', '数据库'), ('operation', '运维/系统/服务器'), ('development', '软件开发')], max_length=30, verbose_name='从属体系')),
            ],
            options={
                'verbose_name': '开发体系词汇',
                'verbose_name_plural': '开发体系词汇',
                'db_table': 'phrase_development_system',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentTools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='词汇名称')),
                ('alias', models.CharField(max_length=50, null=True, verbose_name='词汇别名')),
                ('detail', models.CharField(default='软件开发术语', max_length=70, verbose_name='词汇描述')),
                ('father_type', models.CharField(max_length=50, null=True, verbose_name='父词汇类型')),
                ('root_type', models.CharField(max_length=50, verbose_name='根词汇类型')),
                ('img_url', models.CharField(max_length=100, verbose_name='图片路径')),
                ('system', models.CharField(choices=[('ai', '人工智能'), ('bigdata', '大数据'), ('couldcompute', '云计算'), ('blockchain', '区块链'), ('database', '数据库'), ('operation', '运维/系统/服务器'), ('development', '软件开发')], max_length=30, verbose_name='从属体系')),
            ],
            options={
                'verbose_name': '开发工具',
                'verbose_name_plural': '开发工具',
                'db_table': 'phrase_development_tools',
            },
        ),
        migrations.CreateModel(
            name='FrameworkAndLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='词汇名称')),
                ('alias', models.CharField(max_length=50, null=True, verbose_name='词汇别名')),
                ('detail', models.CharField(default='软件开发术语', max_length=70, verbose_name='词汇描述')),
                ('father_type', models.CharField(max_length=50, null=True, verbose_name='父词汇类型')),
                ('root_type', models.CharField(max_length=50, verbose_name='根词汇类型')),
                ('img_url', models.CharField(max_length=100, verbose_name='图片路径')),
                ('system', models.CharField(choices=[('ai', '人工智能'), ('bigdata', '大数据'), ('couldcompute', '云计算'), ('blockchain', '区块链'), ('database', '数据库'), ('operation', '运维/系统/服务器'), ('development', '软件开发')], max_length=30, verbose_name='从属体系')),
            ],
            options={
                'verbose_name': '框架和库',
                'verbose_name_plural': '框架和库',
                'db_table': 'phrase_framework_and_lib',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='词汇名称')),
                ('alias', models.CharField(max_length=50, null=True, verbose_name='词汇别名')),
                ('detail', models.CharField(default='软件开发术语', max_length=70, verbose_name='词汇描述')),
                ('father_type', models.CharField(max_length=50, null=True, verbose_name='父词汇类型')),
                ('root_type', models.CharField(max_length=50, verbose_name='根词汇类型')),
                ('img_url', models.CharField(max_length=100, verbose_name='图片路径')),
                ('system', models.CharField(choices=[('ai', '人工智能'), ('bigdata', '大数据'), ('couldcompute', '云计算'), ('blockchain', '区块链'), ('database', '数据库'), ('operation', '运维/系统/服务器'), ('development', '软件开发')], max_length=30, verbose_name='从属体系')),
            ],
            options={
                'verbose_name': '编程语言',
                'verbose_name_plural': '编程语言',
                'db_table': 'phrase_language',
            },
        ),
        migrations.CreateModel(
            name='TopUserPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='词汇名称')),
                ('detail', models.CharField(default='软件开发术语', max_length=20, verbose_name='词汇描述')),
                ('img_url', models.CharField(max_length=50, verbose_name='图片路径')),
            ],
            options={
                'verbose_name': '用户热搜词汇',
                'verbose_name_plural': '用户热搜词汇',
                'db_table': 'phrase_top_user',
            },
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='词汇名称')),
                ('alias', models.CharField(max_length=50, null=True, verbose_name='词汇别名')),
                ('detail', models.CharField(default='软件开发术语', max_length=70, verbose_name='词汇描述')),
                ('father_type', models.CharField(max_length=50, null=True, verbose_name='父词汇类型')),
                ('root_type', models.CharField(max_length=50, verbose_name='根词汇类型')),
                ('img_url', models.CharField(max_length=100, verbose_name='图片路径')),
                ('system', models.CharField(choices=[('ai', '人工智能'), ('bigdata', '大数据'), ('couldcompute', '云计算'), ('blockchain', '区块链'), ('database', '数据库'), ('operation', '运维/系统/服务器'), ('development', '软件开发')], max_length=30, verbose_name='从属体系')),
            ],
            options={
                'verbose_name': '相关网站',
                'verbose_name_plural': '相关网站',
                'db_table': 'phrase_website',
            },
        ),
    ]
